name: Publish

on:
  push:
    branches:
      - master
  
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: MPWSimulator.jar
            asset_name: MPW-Simulator-Linux.jar
          - os: windows-latest
            artifact_name: MPWSimulator.jar
            asset_name: MPW-Simulator-Win.jar
          - os: macos-latest
            artifact_name: MPWSimulator.jar
            asset_name: MPW-Simulator-Mac.jar

    steps:
    - uses: actions/checkout@v2
    
    - name: Step 1 - Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Step 2 - Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Step 3 - Upload built jar
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
