# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Publish Maven Package

on:
  push:
    branches:
      - master

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Step 1 - Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Step 2 - Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Step 3 - Upload Application
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/MPWSimulator.jar
        asset_name: MPWSimulator-Ubuntu.jar
        prerelease: false
        overwrite: true
        body: This release is an automatic build.


  build-on-windows:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Step 1 - Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Step 2 - Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Step 3 - Upload Application
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/MPWSimulator.jar
        asset_name: MPWSimulator-Win.jar
        prerelease: false
        overwrite: true
        body: This release is an automatic build.

